services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks: 
      - poc_network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks: 
      - poc_network
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks: 
      - poc_network
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
     
  mongodb:
    image : mongo
    container_name: mongodb
    volumes:
      - /home/barry/mongodb/database:/data/db
    ports:
      - 27017:27017
    networks:
      - poc_network
    restart: unless-stopped
    
  web-api:
    build: 
      context: .
      dockerfile: EventDrivenWebAPIExample.API/Dockerfile
    ports:
      - 8080:80
      - 8090:443
    networks:
      - poc_network
    environment:
      MONGO_DB_NAME: POC
      MONGO_CONNECTION_STRING: mongodb://mongodb:27017
      KAFKA_HOST: kafka:29092
      KAFKA_TOPIC: POC
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - kafka
      - mongodb
      
  kafka-consumer:
    build: 
      context: .
      dockerfile: EventDrivenWebAPIExample.Kafka.ConsumerApp/Dockerfile
    networks:
      - poc_network
    environment:
      MONGO_DB_NAME: POC
      MONGO_CONNECTION_STRING: mongodb://mongodb:27017
      KAFKA_HOST: kafka:29092
      KAFKA_TOPIC: POC
      KAFKA_CONSUMER_GROUP: POC_CONSUMER
    depends_on:
      - kafka
      - mongodb

networks:
  poc_network:
    external: true

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local